add example to docstring
sfu-db/connector-x pull request #56
Opened 2021-03-28 23:18 UTC by Wukkkinz-0725

2021-03-31 04:32 UTC, wangxiaoying commented
Great! Here are a few things that would be better to add:
1. A simple description about how we do the partition in the documentation
2. A sentence about what kind of query our partition method supports (select, project, join) in the documentation
3. One test case for each supported type of query (we already have select in our test, so only queries with project and join operations are needed)

2021-03-31 04:33 UTC, wangxiaoying requested changes
Looks great! Here are a few things that would be better to add:

1. A simple description about how we do the partition in the documentation
2. A sentence about what kind of query our partition method supports (select, project, join) in the documentation
3. One test case for each supported type of query (we already have select in our test, so only queries with project and join operations are needed)

2021-04-01 07:55 UTC, dovahcrow commented
great job! I polished the examples and I think you can continue resolving @wangxiaoying 's comments.

2021-04-13 03:57 UTC, dovahcrow approved these changes

2021-04-13 03:57 UTC, merged